#ifndef DEFAULTS_H
#define DEFAULTS_H

#define DEFAULT_ADDR "::"
#define DEFAULT_PORT 1350
#define DEFAULT_JITTER 16
#define DEFAULT_RATE 48000
#define DEFAULT_CHANNELS 2
#define PAYLOAD_0_REFERENCE_RATE 8000
#define DEFAULT_BUFFER_LENGTH 122880

#endif
